name: GitHub Metrics

on:
  push: { branches: ["master", "main"] }
  schedule:
    - cron: "0 0 * * *" # Scheduled to run once a day at midnight

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, pull_request, issue
          plugin_followup: yes
          plugin_stars: yes
